// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example for Gravel First app. Replace these with your actual Firebase project settings.
/// Get these values from your Firebase Console -> Project Settings -> General -> Your apps
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZo-2lDAgVxL0FNZ5KAtXcz8SssDD3EjM',
    appId: '1:249998235285:web:fc11c40dfddc50c22dad9c',
    messagingSenderId: '249998235285',
    projectId: 'gravel-biking',
    authDomain: 'gravel-biking.firebaseapp.com',
    storageBucket: 'gravel-biking.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZo-2lDAgVxL0FNZ5KAtXcz8SssDD3EjM',
    appId: '1:249998235285:web:fc11c40dfddc50c22dad9c',
    messagingSenderId: '249998235285',
    projectId: 'gravel-biking',
    authDomain: 'gravel-biking.firebaseapp.com',
    storageBucket: 'gravel-biking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZo-2lDAgVxL0FNZ5KAtXcz8SssDD3EjM',
    appId: '1:249998235285:web:fc11c40dfddc50c22dad9c',
    messagingSenderId: '249998235285',
    projectId: 'gravel-biking',
    authDomain: 'gravel-biking.firebaseapp.com',
    storageBucket: 'gravel-biking.firebasestorage.app',
    iosBundleId: 'com.aoli.gravel_biking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZo-2lDAgVxL0FNZ5KAtXcz8SssDD3EjM',
    appId: '1:249998235285:web:fc11c40dfddc50c22dad9c',
    messagingSenderId: '249998235285',
    projectId: 'gravel-biking',
    authDomain: 'gravel-biking.firebaseapp.com',
    storageBucket: 'gravel-biking.firebasestorage.app',
    iosBundleId: 'com.aoli.gravel_biking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZo-2lDAgVxL0FNZ5KAtXcz8SssDD3EjM',
    appId: '1:249998235285:web:fc11c40dfddc50c22dad9c',
    messagingSenderId: '249998235285',
    projectId: 'gravel-biking',
    authDomain: 'gravel-biking.firebaseapp.com',
    storageBucket: 'gravel-biking.firebasestorage.app',
  );
}
