// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example for Gravel First app. Replace these with your actual Firebase project settings.
/// Get these values from your Firebase Console -> Project Settings -> General -> Your apps
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZo-2lDAgVxL0FNZ5KAtXcz8SssDD3EjM',
    appId: 'your-web-app-id-here',
    messagingSenderId: 'your-sender-id-here',
    projectId: 'gravel-biking',
    authDomain: 'your-project-id-here.firebaseapp.com',
    storageBucket: 'your-project-id-here.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your-android-api-key-here',
    appId: 'your-android-app-id-here',
    messagingSenderId: 'your-sender-id-here',
    projectId: 'your-project-id-here',
    storageBucket: 'your-project-id-here.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key-here',
    appId: 'your-ios-app-id-here',
    messagingSenderId: 'your-sender-id-here',
    projectId: 'your-project-id-here',
    storageBucket: 'your-project-id-here.firebasestorage.app',
    iosBundleId: 'com.example.gravel_biking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-ios-api-key-here',
    appId: 'your-ios-app-id-here',
    messagingSenderId: 'your-sender-id-here',
    projectId: 'your-project-id-here',
    storageBucket: 'your-project-id-here.firebasestorage.app',
    iosBundleId: 'com.example.gravel_biking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your-web-api-key-here',
    appId: 'your-windows-app-id-here',
    messagingSenderId: 'your-sender-id-here',
    projectId: 'your-project-id-here',
    authDomain: 'your-project-id-here.firebaseapp.com',
    storageBucket: 'your-project-id-here.firebasestorage.app',
  );
}
